# make file for first assingment of cs162
# remember to use tabs or it gets mad
CC = g++
exe_file = assignment1
$(exe_file): assignment1.cpp header1.cpp
	$(CC) assignment1.cpp header1.cpp -o $(exe_file)
